spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/cook_book
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hidden-method:
      filter:
        enabled: true